# Generated by Django 4.0.5 on 2022-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movieseries',
            name='genre',
            field=models.CharField(default='NaN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movieseries',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
