# Generated by Django 4.0.5 on 2022-06-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provider_movieseries_poster_movieseries_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieseries',
            name='providers',
        ),
    ]
