# Generated by Django 4.0.5 on 2022-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_movieseries_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[(1, 'streaming'), (2, 'rental'), (3, 'unavailable')], default='unavailable', max_length=255),
        ),
    ]
