# Generated by Django 4.0.5 on 2022-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieseries',
            name='providers',
            field=models.ManyToManyField(to='core.provider'),
        ),
    ]
