# Generated by Django 4.0.5 on 2022-06-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movieseries_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='provider', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.URLField(default='unavailable'),
        ),
    ]
