# Generated by Django 4.0.5 on 2022-06-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_provider_name_alter_provider_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='provider_name',
        ),
    ]
