# Generated by Django 4.0.5 on 2022-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_name_provider_provider_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='provider_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='movieseries',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='icon',
            field=models.URLField(default='unavailable'),
        ),
        migrations.AlterField(
            model_name='movieseries',
            name='poster',
            field=models.URLField(blank=True, default='unavailable'),
        ),
    ]
