# Generated by Django 4.0.5 on 2022-06-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='movie_serie',
            new_name='movie_series',
        ),
    ]
