# Generated by Django 4.0.5 on 2022-06-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_movie_serie_watchlist_movie_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('1', 'streaming'), ('2', 'rental'), ('3', 'unavailable')], default='unavailable', max_length=255),
        ),
    ]
